### ISSUE TITLE
dev or prod deployment on AWS lambda does not work correctly, back button fails

### ISSUE THREAD

**Issue by PhilAndrew** [phlogisticfugu/perfect-paca#3]
After deployment to AWS lambda dev, load the page in browser, well first there are errors related to the /dev or /prod at the URL.
eg. my URL is https://53i9fm8cgk.execute-api.us-east-1.amazonaws.com/dev

The first problem is that resources don't load correctly, I need to add this to nuxt.config.js
  router: {
    base: '/dev/'
  },
Then also
    return axios.get('/api/hello-world')
needs to be
    return axios.get('/dev/api/hello-world')

The second problem is that with the above, pages load when browser loads then but if I go to the first page, then click "hello" link, then press back button a Javascript error occurs.

The Javascript error is then

```
vendor.bundle.a5b598801c8d91968172.js:16 TypeError: Cannot read property 'transition' of undefined
    at nuxt.bundle.adcd921cbe1aacfd92e4.js:1
    at Array.map (<anonymous>)
    at r (nuxt.bundle.adcd921cbe1aacfd92e4.js:1)
    at oe.a (nuxt.bundle.adcd921cbe1aacfd92e4.js:1)
    at d (vendor.bundle.a5b598801c8d91968172.js:16)
    at r (vendor.bundle.a5b598801c8d91968172.js:16)
    at vendor.bundle.a5b598801c8d91968172.js:16
    at vendor.bundle.a5b598801c8d91968172.js:16
    at nuxt.bundle.adcd921cbe1aacfd92e4.js:1
    at <anonymous>

```

**Comment by PhilAndrew** [comment]
Now suddenly my back button javascript error has gone away and I don't know why.

**Comment by PhilAndrew** [comment]
Ok I see a difference between
https://53i9fm8cgk.execute-api.us-east-1.amazonaws.com/dev/
and
https://53i9fm8cgk.execute-api.us-east-1.amazonaws.com/dev

If I leave off the trailing / on the URL then the Javascript error occurs on the back button press.

**Comment by PhilAndrew** [comment]
Ok so the solution is for the back button to change base in nuxt.conf.js to /dev , NOT a /dev/
    base: '/dev'

**Comment by phlogisticfugu** [comment]
Thanks for trying perfect-pace out and digging into it @PhilAndrew !  did you find that you ended up needing to change nuxt.conf.js with a per-stage (dev or prod) setting?

You aren't supposed to have to muck with nuxt.conf.js, so if you found that you needed to do that, would want to know.
